import type { EnemyDef } from '@/shared/types';

/**
 * `reactionDelayS` is the most important tuning knob in this file. Enemies
 * that respond instantly read as aimbots; 0.2-0.4s of hesitation reads as
 * intelligence and creates the openings that make combat legible.
 */
export const ENEMY_DEFS: EnemyDef[] = [
  {
    id: 'grasshopper',
    name: 'Reach Grasshopper',
    tier: 'chaff',
    level: 2,
    baseStats: { hp: 40, atk: 6, def: 2, staggerMax: 60 },
    ai: {
      aggroRadius: 13,
      leashRadius: 26,
      attackRange: 2.2,
      moveSpeed: 3.6,
      turnSpeed: 5,
      reactionDelayS: 0.2,
      fleeAtHpPct: 0,
    },
    attacks: [
      {
        id: 'bite',
        weight: 100,
        windupS: 0.45,
        activeS: 0.12,
        recoverS: 0.5,
        multiplier: 1.0,
        range: 2.4,
        arcDeg: 70,
        stagger: 8,
        cooldownS: 1.6,
        telegraph: 'cone',
        element: 'physical',
      },
    ],
    dropTable: 'dt_grasshopper',
    visual: { color: 0x8fd94f, accent: 0xe8ff8a, scale: 0.85, shape: 'insectoid' },
  },
  {
    id: 'rockhide_sentinel',
    name: 'Rockhide Sentinel',
    tier: 'bruiser',
    level: 6,
    baseStats: { hp: 220, atk: 18, def: 30, staggerMax: 180 },
    ai: {
      aggroRadius: 14,
      leashRadius: 28,
      attackRange: 3.2,
      moveSpeed: 2.4,
      turnSpeed: 2.0,
      reactionDelayS: 0.35,
      fleeAtHpPct: 0,
    },
    attacks: [
      {
        id: 'slam',
        weight: 70,
        windupS: 1.2,
        activeS: 0.2,
        recoverS: 0.9,
        multiplier: 1.6,
        range: 3.4,
        arcDeg: 360,
        stagger: 20,
        cooldownS: 3.5,
        telegraph: 'ring',
        element: 'physical',
      },
      {
        id: 'sweep',
        weight: 30,
        windupS: 0.8,
        activeS: 0.3,
        recoverS: 0.7,
        multiplier: 1.1,
        range: 4.2,
        arcDeg: 180,
        stagger: 12,
        cooldownS: 6.0,
        telegraph: 'cone',
        element: 'physical',
      },
    ],
    dropTable: 'dt_rockhide',
    visual: { color: 0x8a6b4f, accent: 0xffb347, scale: 1.5, shape: 'golem' },
  },
  {
    id: 'warden_zhun',
    name: 'Warden Zhun',
    tier: 'midboss',
    level: 7,
    baseStats: { hp: 1400, atk: 24, def: 38, staggerMax: 400 },
    ai: {
      aggroRadius: 40,
      leashRadius: 999, // Boss arenas do not leash.
      attackRange: 3.6,
      moveSpeed: 3.0,
      turnSpeed: 2.6,
      reactionDelayS: 0.3,
      fleeAtHpPct: 0,
    },
    attacks: [
      {
        id: 'lunge',
        weight: 45,
        windupS: 0.75,
        activeS: 0.18,
        recoverS: 0.65,
        multiplier: 1.4,
        range: 4.4,
        arcDeg: 90,
        stagger: 18,
        cooldownS: 2.6,
        telegraph: 'cone',
        element: 'physical',
      },
      {
        id: 'water_jet',
        weight: 35,
        windupS: 1.0,
        activeS: 0.25,
        recoverS: 0.8,
        multiplier: 1.2,
        range: 12,
        arcDeg: 18,
        stagger: 10,
        cooldownS: 4.5,
        telegraph: 'line',
        element: 'energy',
      },
      {
        id: 'tide_crash',
        weight: 40,
        windupS: 1.35,
        activeS: 0.3,
        recoverS: 1.1,
        multiplier: 1.9,
        range: 7.5,
        arcDeg: 360,
        stagger: 30,
        cooldownS: 6.5,
        telegraph: 'ring',
        element: 'energy',
      },
    ],
    phases: [
      { hpAbove: 0.5, attacks: ['lunge', 'water_jet'], moveSpeed: 3.0 },
      {
        hpAbove: 0,
        attacks: ['lunge', 'water_jet', 'tide_crash'],
        moveSpeed: 3.6,
        damageMul: 1.2,
        onEnter: 'roar',
      },
    ],
    dropTable: 'dt_warden_zhun',
    visual: { color: 0x4fb8d9, accent: 0xd9f7ff, scale: 2.0, shape: 'warden' },
  },
];

export const ENEMY_MAP: Map<string, EnemyDef> = new Map(
  ENEMY_DEFS.map((d) => [d.id, d]),
);
