#!/usr/bin/env python3
"""Bundle the multi-file obfuscator into self-contained Luau ModuleScripts.

Roblox ModuleScripts cannot `require` by relative filesystem path, so we inline
every module into one file behind a tiny synchronous module loader. Module keys
are file basenames (unique across the tree). `export type` is rewritten to plain
`type` since the bodies become function scopes.

Produces two bundles:
  dist/Clovexx.luau  — source-level obfuscator (root: Obfuscator)
  dist/Clovyre.luau  — VM/bytecode obfuscator (root: Clovyre), incl. Clovexx
                       fallback so a single file covers both.
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))

CLOVEXX_MODULES = [
    ("Lexer", "src/Lexer.luau"),
    ("Parser", "src/Parser.luau"),
    ("Serializer", "src/Serializer.luau"),
    ("NameGen", "src/NameGen.luau"),
    ("Rename", "src/passes/Rename.luau"),
    ("StringEncrypt", "src/passes/StringEncrypt.luau"),
    ("NumberEncode", "src/passes/NumberEncode.luau"),
    ("Junk", "src/passes/Junk.luau"),
    ("Obfuscator", "src/Obfuscator.luau"),
]

VM_MODULES = [
    ("Opcodes", "src/vm/Opcodes.luau"),
    ("Compiler", "src/vm/Compiler.luau"),
    ("Runtime", "src/vm/Runtime.luau"),
    ("Clovyre", "src/Clovyre.luau"),
]

REQUIRE_RE = re.compile(r'require\(\s*"[^"]*?/([A-Za-z0-9_]+)"\s*\)')

def transform(body: str) -> str:
    body = REQUIRE_RE.sub(lambda m: f'__cx_require("{m.group(1)}")', body)
    body = body.replace("export type", "type")
    return body

def build(name: str, modules, root: str, title: str) -> str:
    out = []
    out.append("--!nolint")
    out.append(f"-- {title}")
    out.append("-- Generated by build.py from src/. Do not edit by hand.")
    out.append(f"-- Usage: local {name} = require(path.to.{name})")
    out.append(f"--        local obf = {name}.obfuscate(sourceString, {{ seed = 123 }})")
    out.append("")
    out.append("local __cx_modules = {}")
    out.append("local __cx_cache = {}")
    out.append("local function __cx_require(name)")
    out.append("\tlocal c = __cx_cache[name]")
    out.append("\tif c ~= nil then return c.value end")
    out.append("\tlocal factory = __cx_modules[name]")
    out.append('\tif factory == nil then error("bundle: unknown module " .. tostring(name)) end')
    out.append("\tlocal value = factory()")
    out.append("\t__cx_cache[name] = { value = value }")
    out.append("\treturn value")
    out.append("end")
    out.append("")
    for modname, rel in modules:
        with open(os.path.join(HERE, rel), "r") as f:
            body = transform(f.read())
        out.append(f'__cx_modules["{modname}"] = function()')
        out.append(body.rstrip("\n"))
        out.append("end")
        out.append("")
    out.append(f'return __cx_require("{root}")')
    out.append("")

    dist = os.path.join(HERE, "dist")
    os.makedirs(dist, exist_ok=True)
    path = os.path.join(dist, name + ".luau")
    with open(path, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {path} ({os.path.getsize(path)} bytes)")
    return path

def main():
    build("Clovexx", CLOVEXX_MODULES, "Obfuscator",
          "Clovexx — Luau source-level obfuscator (bundled, single ModuleScript).")
    # Clovyre needs the Clovexx modules too (for fallback + protect mode).
    build("Clovyre", CLOVEXX_MODULES + VM_MODULES, "Clovyre",
          "Clovyre — Luau VM/bytecode obfuscator (bundled, single ModuleScript).")

if __name__ == "__main__":
    main()
