#!/usr/bin/env python3
"""Bundle the multi-file obfuscator into a single self-contained Luau ModuleScript.

Roblox ModuleScripts cannot `require` by relative filesystem path, so we inline
every module into one file behind a tiny synchronous module loader. Module keys
are file basenames (unique across the tree). `export type` is rewritten to plain
`type` since the bodies become function scopes.
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "src")

# Order doesn't matter for definitions; the loader resolves lazily.
MODULES = [
    ("Lexer", "src/Lexer.luau"),
    ("Parser", "src/Parser.luau"),
    ("Serializer", "src/Serializer.luau"),
    ("NameGen", "src/NameGen.luau"),
    ("Rename", "src/passes/Rename.luau"),
    ("StringEncrypt", "src/passes/StringEncrypt.luau"),
    ("NumberEncode", "src/passes/NumberEncode.luau"),
    ("Junk", "src/passes/Junk.luau"),
    ("Obfuscator", "src/Obfuscator.luau"),
]

REQUIRE_RE = re.compile(r'require\(\s*"[^"]*?/([A-Za-z0-9_]+)"\s*\)')

def transform(body: str) -> str:
    # rewrite require("...path.../Name") -> __clovexx_require("Name")
    body = REQUIRE_RE.sub(lambda m: f'__clovexx_require("{m.group(1)}")', body)
    # export type -> type (valid inside a function scope)
    body = body.replace("export type", "type")
    return body

def main():
    out = []
    out.append("--!nolint")
    out.append("-- Clovexx — Luau obfuscator (bundled, single ModuleScript).")
    out.append("-- Generated by build.py from src/. Do not edit by hand.")
    out.append("-- Usage: local Clovexx = require(path.to.Clovexx)")
    out.append("--        local obf = Clovexx.obfuscate(sourceString, { seed = 123 })")
    out.append("")
    out.append("local __clovexx_modules = {}")
    out.append("local __clovexx_cache = {}")
    out.append("local function __clovexx_require(name)")
    out.append("\tlocal c = __clovexx_cache[name]")
    out.append("\tif c ~= nil then return c.value end")
    out.append("\tlocal factory = __clovexx_modules[name]")
    out.append('\tif factory == nil then error("Clovexx: unknown module " .. tostring(name)) end')
    out.append("\tlocal value = factory()")
    out.append("\t__clovexx_cache[name] = { value = value }")
    out.append("\treturn value")
    out.append("end")
    out.append("")
    for name, rel in MODULES:
        with open(os.path.join(HERE, rel), "r") as f:
            body = transform(f.read())
        out.append(f'__clovexx_modules["{name}"] = function()')
        out.append(body.rstrip("\n"))
        out.append("end")
        out.append("")
    out.append('return __clovexx_require("Obfuscator")')
    out.append("")

    dist = os.path.join(HERE, "dist")
    os.makedirs(dist, exist_ok=True)
    path = os.path.join(dist, "Clovexx.luau")
    with open(path, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {path} ({os.path.getsize(path)} bytes)")

if __name__ == "__main__":
    main()
