#!/bin/sh
# Builds LUCK_PRIVATE.lua = the public script + the theme engine.
#
# The private build is never edited by hand. Change LUCK_fast.lua or
# private/theme.lua and re-run this, so the two can never drift.
set -e
root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/LUCK_PRIVATE.lua"
{
    printf -- '-- LUCK PRIVATE  ·  built from LUCK_fast.lua + private/theme.lua\n'
    printf -- '-- Do not edit this file. Edit the sources and run private/build.sh.\n'
    cat "$root/LUCK_fast.lua"
    cat "$root/private/theme.lua"
} > "$out"
printf 'built %s (%s lines)\n' "$out" "$(wc -l < "$out" | tr -d ' ')"
